# fly.toml app configuration file generated for callisto-bot on 2023-10-16T22:50:00-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "callisto-bot"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
